apiVersion: v1
kind: Secret
metadata:
  name: gotrue-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app: gotrue
type: Opaque
stringData:
  GOTRUE_JWT_SECRET: {{ .Values.gotrue.jwtSecret | quote }}
  GOTRUE_DB_DATABASE_URL: {{ include "platform.gotrueDbUrl" . | quote }}
