apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
  type: ClusterIP
