apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app: postgres
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.superuserPassword | quote }}
  APP_USER_PASSWORD: {{ .Values.postgres.appUserPassword | quote }}
  AUTH_ADMIN_PASSWORD: {{ .Values.postgres.authAdminPassword | quote }}
  DATABASE_URL: {{ include "platform.appDbUrl" . | quote }}
