apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initscripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
data:
  99-roles.sql: |
    \set pgpass `echo "$POSTGRES_PASSWORD"`
    ALTER USER authenticator          WITH PASSWORD :'pgpass';
    ALTER USER supabase_auth_admin    WITH PASSWORD :'pgpass';
    ALTER USER supabase_storage_admin WITH PASSWORD :'pgpass';
